version: '3.8'

services:
  app:
    build: . # Constr√≥i a imagem a partir do Dockerfile na raiz do projeto
    container_name: menu-manager-app
    ports:
      - '8080:8080'
    env_file:
      - ./.env
