cache:
  ttl:
    get:
      item:
        by-id: ${CACHE_TTL_GET_ITEM_BY_ID:300} # 5 minutos em segundos
        by-category: ${CACHE_TTL_ITEM_BY_CATEGORY:300} # 5 minutos em segundos
      category:
        all:  ${CACHE_TTL_GET_ALL_CATEGORIES:300} # 5 minutos em segundos
        by-id: ${CACHE_TTL_GET_CATEGORY_BY_ID:300} # 5 minutos em segundos

spring:
  profiles:
    active: "" # Para ativar a segurança, deixe em branco ou remova a linha
   # active: "no-auth" # Para desativar a segurança, use esta linha
  datasource:
    url: jdbc:postgresql://localhost:5432/menu_manager
    username: ${BD_USERNAME:admin}
    password: ${BD_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: /db/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: zB8ULkhG1UViwskFdxN1K47wnTTlyIS-B7WboEcycsI=%

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET}